/* The following code was generated by JFlex 1.4.3 on 16.04.12 21:05 */

package pl.wcislo.sbql4j.lang.parser; 
  
import java_cup.runtime.Symbol;
import pl.wcislo.sbql4j.lang.parser.SBQLSymbolFactory;

import static pl.wcislo.sbql4j.lang.parser.ParserSym.*;
 



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 16.04.12 21:05 from the specification file
 * <tt>C:/_java/_workspaces20110601115450/NCBiR/SBQL4J/sbql_src/pl/wcislo/sbql4j/lang/parser/lexer.lex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int IDENTIFIER = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\26\1\25\1\0\1\26\1\24\22\0\1\76\1\35\1\22"+
    "\1\0\1\14\1\33\1\54\1\23\1\36\1\37\1\31\1\27\1\103"+
    "\1\30\1\21\1\32\12\1\1\117\1\116\1\102\1\34\1\44\1\120"+
    "\1\0\1\51\1\100\1\72\1\53\1\67\1\110\1\62\1\105\1\65"+
    "\1\111\1\13\1\113\1\57\1\52\1\45\1\75\1\66\1\46\1\55"+
    "\1\73\1\56\1\61\1\104\1\71\1\114\1\13\1\42\1\0\1\43"+
    "\1\0\1\12\1\0\1\7\1\101\1\74\1\17\1\5\1\6\1\64"+
    "\1\107\1\15\1\112\1\13\1\10\1\60\1\16\1\47\1\77\1\70"+
    "\1\3\1\11\1\2\1\4\1\63\1\106\1\20\1\115\1\13\1\40"+
    "\1\50\1\41\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\7\2\1\0\3\2\1\3\2\0\2\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\0\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\2\2\1\0"+
    "\3\2\1\0\14\2\1\22\1\23\5\2\1\24\1\25"+
    "\1\26\1\0\7\2\1\27\5\2\1\0\1\30\3\2"+
    "\1\31\1\32\1\0\1\33\1\34\1\35\3\36\1\2"+
    "\1\27\5\2\1\37\13\2\1\30\7\2\1\40\5\2"+
    "\1\41\6\2\1\42\1\43\1\37\1\44\1\45\1\2"+
    "\1\46\1\2\1\0\2\2\1\47\1\12\2\2\1\50"+
    "\10\2\1\51\2\52\11\2\1\53\5\2\1\54\7\2"+
    "\1\0\3\2\1\55\26\2\1\56\1\57\1\60\5\2"+
    "\1\0\2\2\1\61\5\2\1\62\5\2\1\63\2\2"+
    "\1\64\1\2\1\65\1\66\1\2\1\67\4\2\2\0"+
    "\1\2\2\0\2\2\2\0\1\2\1\70\3\2\2\0"+
    "\1\2\2\0\2\2\2\0\1\71\2\2\1\72\1\73"+
    "\2\2\1\74\1\75\2\2\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[278];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\121\0\242\0\363\0\u0144\0\u0195\0\u01e6\0\u0237"+
    "\0\u0288\0\u02d9\0\u032a\0\u037b\0\u03cc\0\u041d\0\u046e\0\u04bf"+
    "\0\u0510\0\u0561\0\121\0\121\0\121\0\121\0\121\0\121"+
    "\0\u05b2\0\u0603\0\121\0\121\0\121\0\121\0\121\0\121"+
    "\0\u0654\0\u06a5\0\u06f6\0\u0747\0\u0798\0\u07e9\0\u083a\0\u088b"+
    "\0\u08dc\0\u092d\0\u097e\0\u09cf\0\u0a20\0\u0a71\0\u0ac2\0\u0b13"+
    "\0\u0b64\0\u0bb5\0\u0c06\0\u0c57\0\u0ca8\0\121\0\u0cf9\0\u0d4a"+
    "\0\u0d9b\0\u0dec\0\u0e3d\0\121\0\121\0\121\0\u0e8e\0\u0edf"+
    "\0\u0f30\0\u0f81\0\u0fd2\0\u1023\0\u1074\0\u10c5\0\u1116\0\u1167"+
    "\0\u11b8\0\u1209\0\u125a\0\u12ab\0\u12fc\0\u134d\0\u139e\0\u13ef"+
    "\0\u1440\0\121\0\121\0\u1491\0\121\0\121\0\121\0\u14e2"+
    "\0\u1533\0\121\0\u1584\0\u15d5\0\u1626\0\u1677\0\u16c8\0\u1719"+
    "\0\u176a\0\121\0\u17bb\0\u180c\0\u185d\0\u18ae\0\u18ff\0\u1950"+
    "\0\u19a1\0\u19f2\0\u1a43\0\u1a94\0\u1ae5\0\u1b36\0\u1b87\0\u1bd8"+
    "\0\u1c29\0\u1c7a\0\u1ccb\0\u1d1c\0\u1d6d\0\121\0\u1dbe\0\u1e0f"+
    "\0\u1e60\0\u1eb1\0\u1f02\0\u0e8e\0\u1f53\0\u1fa4\0\u1ff5\0\u2046"+
    "\0\u2097\0\u20e8\0\u0144\0\u0144\0\u0144\0\u0144\0\u0144\0\u2139"+
    "\0\u0144\0\u218a\0\u21db\0\u222c\0\u227d\0\u0144\0\u0144\0\u22ce"+
    "\0\u231f\0\121\0\u2370\0\u23c1\0\u2412\0\u2463\0\u24b4\0\u2505"+
    "\0\u2556\0\u25a7\0\u0144\0\u25f8\0\u2649\0\u269a\0\u26eb\0\u273c"+
    "\0\u278d\0\u27de\0\u282f\0\u2880\0\u28d1\0\u2922\0\u0144\0\u2973"+
    "\0\u29c4\0\u2a15\0\u2a66\0\u2ab7\0\u0144\0\u2b08\0\u2b59\0\u2baa"+
    "\0\u2bfb\0\u2c4c\0\u2c9d\0\u2cee\0\u2d3f\0\u2d90\0\u2de1\0\u2e32"+
    "\0\u0144\0\u2e83\0\u2ed4\0\u2f25\0\u2f76\0\u2fc7\0\u3018\0\u3069"+
    "\0\u30ba\0\u310b\0\u315c\0\u31ad\0\u31fe\0\u324f\0\u32a0\0\u32f1"+
    "\0\u3342\0\u3393\0\u33e4\0\u3435\0\u3486\0\u34d7\0\u3528\0\u0144"+
    "\0\u0144\0\u0144\0\u3579\0\u35ca\0\u361b\0\u366c\0\u36bd\0\u370e"+
    "\0\u375f\0\u37b0\0\u0144\0\u3801\0\u3852\0\u38a3\0\u38f4\0\u3945"+
    "\0\u0144\0\u3996\0\u39e7\0\u3a38\0\u3a89\0\u3ada\0\u0144\0\u3b2b"+
    "\0\u3b7c\0\u0144\0\u3bcd\0\u0144\0\u0144\0\u3c1e\0\u0144\0\u3c6f"+
    "\0\121\0\u3cc0\0\u3d11\0\u3d62\0\u3db3\0\u3e04\0\u3e55\0\u3ea6"+
    "\0\u3ef7\0\u3f48\0\u3f99\0\u3fea\0\u403b\0\u0144\0\u408c\0\u40dd"+
    "\0\u412e\0\u417f\0\u41d0\0\u4221\0\u4272\0\u42c3\0\u4314\0\u4365"+
    "\0\u43b6\0\u4407\0\u0144\0\u4458\0\u44a9\0\121\0\121\0\u44fa"+
    "\0\u454b\0\121\0\u0144\0\u459c\0\u45ed\0\u0144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[278];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\5\1\12\2\5\1\13\1\14\1\15\1\16\1\5"+
    "\1\17\1\20\1\21\1\22\2\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\5\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\5"+
    "\1\55\1\5\1\56\1\57\1\5\1\60\2\5\1\61"+
    "\1\5\1\62\1\5\1\23\1\5\1\63\1\64\1\65"+
    "\1\66\1\67\1\5\1\70\1\5\1\71\1\72\1\73"+
    "\3\5\1\74\1\75\1\76\122\0\1\3\17\0\1\77"+
    "\100\0\2\5\1\100\6\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\10\5\1\101\1\0\1\5\1\0"+
    "\1\5\1\102\2\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\3\5\1\103\24\0\3\5\1\0\3\5"+
    "\1\0\21\5\1\0\3\5\2\0\12\5\4\0\6\5"+
    "\1\104\2\5\1\0\1\5\1\0\4\5\24\0\2\5"+
    "\1\105\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\7\5\1\106\1\107\1\0\1\5\1\0"+
    "\1\5\1\110\2\5\24\0\3\5\1\0\3\5\1\0"+
    "\6\5\1\111\12\5\1\0\3\5\2\0\12\5\4\0"+
    "\1\5\1\112\1\5\1\113\1\114\4\5\1\0\1\5"+
    "\1\0\4\5\24\0\3\5\1\0\3\5\1\0\21\5"+
    "\1\0\3\5\2\0\12\5\20\0\1\115\104\0\11\5"+
    "\1\0\1\5\1\0\1\5\1\116\2\5\24\0\3\5"+
    "\1\0\3\5\1\0\21\5\1\0\3\5\2\0\12\5"+
    "\4\0\4\5\1\117\4\5\1\0\1\5\1\0\4\5"+
    "\24\0\2\5\1\120\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\4\5\1\121\4\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\24\0\1\122\77\0"+
    "\22\20\1\123\76\20\22\124\1\0\76\124\25\0\1\23"+
    "\127\0\1\125\120\0\1\126\120\0\1\127\65\0\11\5"+
    "\1\0\1\5\1\0\4\5\24\0\1\5\1\130\1\5"+
    "\1\0\3\5\1\0\21\5\1\0\3\5\2\0\12\5"+
    "\4\0\2\5\1\131\6\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\53\0\1\132\51\0\11\5\1\0\1\5"+
    "\1\0\4\5\24\0\3\5\1\0\1\5\1\133\1\5"+
    "\1\0\1\134\3\5\1\135\14\5\1\0\3\5\2\0"+
    "\7\5\1\136\2\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\1\137\2\5\1\0\3\5\1\0\12\5"+
    "\1\140\6\5\1\0\3\5\2\0\12\5\4\0\11\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\12\5\1\141\6\5\1\0\3\5\2\0\12\5"+
    "\57\0\1\142\45\0\11\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\1\5\1\143\10\5"+
    "\1\144\3\5\1\145\2\5\1\0\3\5\2\0\12\5"+
    "\4\0\11\5\1\0\1\5\1\0\4\5\24\0\3\5"+
    "\1\0\1\5\1\146\1\5\1\0\1\147\20\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\1\150\2\5\1\0\10\5"+
    "\1\151\10\5\1\0\3\5\2\0\12\5\4\0\6\5"+
    "\1\152\2\5\1\0\1\5\1\0\1\153\3\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\1\5\1\154\1\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\2\5\1\155\6\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\1\5\1\156"+
    "\1\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\14\5\1\157\4\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\1\160\2\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\7\5\1\161\2\5\4\0\7\5\1\162\1\5"+
    "\1\0\1\5\1\0\4\5\24\0\2\5\1\163\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\1\164\2\5\1\0\21\5\1\0\3\5\2\0\12\5"+
    "\4\0\6\5\1\165\2\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\37\0\1\166\65\0\11\5\1\0\1\5"+
    "\1\0\4\5\24\0\3\5\1\0\3\5\1\0\21\5"+
    "\1\0\3\5\2\0\1\5\1\167\10\5\4\0\11\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\21\5\1\0\3\5\2\0\3\5\1\170\6\5"+
    "\4\0\11\5\1\0\1\5\1\0\4\5\24\0\1\171"+
    "\2\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\1\172\2\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\4\5"+
    "\24\0\2\5\1\173\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\1\174\120\0\3\5\1\175"+
    "\5\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\1\176\3\5\24\0\3\5"+
    "\1\0\3\5\1\0\21\5\1\0\3\5\2\0\12\5"+
    "\4\0\11\5\1\0\1\5\1\0\1\177\3\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\1\200\3\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\7\5\1\201\1\5\1\0\1\5"+
    "\1\0\4\5\24\0\3\5\1\0\3\5\1\0\21\5"+
    "\1\0\3\5\2\0\12\5\4\0\2\5\1\202\6\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\21\5\1\0\3\5\2\0\12\5\4\0\7\5"+
    "\1\203\1\5\1\0\1\5\1\0\4\5\24\0\3\5"+
    "\1\0\3\5\1\0\21\5\1\0\3\5\2\0\12\5"+
    "\4\0\11\5\1\0\1\5\1\0\4\5\24\0\3\5"+
    "\1\0\3\5\1\0\17\5\1\204\1\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\2\5"+
    "\1\205\1\5\24\0\3\5\1\0\3\5\1\0\21\5"+
    "\1\0\3\5\2\0\11\5\1\206\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\7\5\1\207\11\5\1\0\3\5\2\0\12\5\4\0"+
    "\2\5\1\210\6\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\3\5\1\211\15\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\13\5\1\212"+
    "\5\5\1\0\3\5\2\0\12\5\21\0\1\213\103\0"+
    "\1\5\1\214\6\5\1\215\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\2\5\1\216\7\5\4\0\1\5\1\217\7\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\21\5\1\0\3\5\2\0\12\5\4\0\2\5"+
    "\1\220\5\5\1\221\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\26\0\1\222\76\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\2\5\1\223\1\0\21\5"+
    "\1\0\3\5\2\0\12\5\4\0\11\5\1\0\1\5"+
    "\1\0\2\5\1\224\1\5\24\0\3\5\1\0\3\5"+
    "\1\0\21\5\1\0\3\5\2\0\12\5\4\0\11\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\2\5"+
    "\1\205\1\0\21\5\1\0\3\5\2\0\10\5\1\206"+
    "\1\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\15\5\1\204\3\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\5\5\1\207"+
    "\13\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\7\5\1\203\2\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\16\5\1\217\2\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\1\216\11\5\4\0\11\5\1\0\1\5\1\0\4\5"+
    "\24\0\1\5\1\225\1\5\1\0\3\5\1\0\1\226"+
    "\20\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\2\5\1\211\16\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\11\5\1\227\7\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\1\5\1\230\1\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\10\5\1\231"+
    "\10\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\10\5\1\232\10\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\14\5\1\233\4\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\1\5\1\234\1\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\3\5\1\233\24\0\3\5\1\0\3\5\1\0\21\5"+
    "\1\0\3\5\2\0\12\5\4\0\11\5\1\0\1\5"+
    "\1\0\1\5\1\235\2\5\24\0\3\5\1\0\3\5"+
    "\1\0\21\5\1\0\3\5\2\0\12\5\4\0\11\5"+
    "\1\0\1\5\1\0\4\5\24\0\1\236\2\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\2\5\1\237"+
    "\1\0\3\5\1\0\21\5\1\0\3\5\2\0\12\5"+
    "\4\0\11\5\1\0\1\5\1\0\4\5\24\0\3\5"+
    "\1\0\3\5\1\0\1\240\15\5\1\241\2\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\10\5\1\242"+
    "\10\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\1\5\1\243\17\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\1\244\2\5"+
    "\1\0\3\5\1\0\21\5\1\0\3\5\2\0\12\5"+
    "\4\0\11\5\1\0\1\5\1\0\4\5\24\0\2\5"+
    "\1\245\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\3\5\1\246\5\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\5\5\1\247"+
    "\13\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\7\5\1\247\11\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\12\5\1\250\6\5\1\0\3\5\2\0"+
    "\12\5\4\0\4\5\1\251\4\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\1\5\1\252\1\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\10\5\1\253\10\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\1\254\3\5\24\0\3\5"+
    "\1\0\3\5\1\0\21\5\1\0\3\5\2\0\12\5"+
    "\4\0\4\5\1\255\4\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\1\5"+
    "\1\256\2\5\24\0\3\5\1\0\3\5\1\0\21\5"+
    "\1\0\3\5\2\0\12\5\4\0\11\5\1\0\1\5"+
    "\1\0\4\5\24\0\2\5\1\257\1\0\3\5\1\0"+
    "\13\5\1\260\5\5\1\0\3\5\2\0\12\5\4\0"+
    "\10\5\1\261\1\0\1\5\1\0\4\5\24\0\3\5"+
    "\1\0\3\5\1\0\21\5\1\0\3\5\2\0\12\5"+
    "\4\0\10\5\1\175\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\4\5\1\262\4\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\3\5\1\263\5\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\3\5\1\264"+
    "\5\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\22\0"+
    "\1\265\102\0\4\5\1\266\4\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\1\5\1\267\7\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\4\5\1\270"+
    "\4\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\17\5\1\271\1\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\12\5\1\272\6\5\1\0"+
    "\3\5\2\0\12\5\4\0\4\5\1\273\4\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\12\5\1\274\6\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\15\5\1\271\3\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\1\5\1\275\17\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\1\5\1\276"+
    "\17\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\1\277\2\5\1\0\3\5"+
    "\1\0\11\5\1\300\7\5\1\0\3\5\2\0\12\5"+
    "\4\0\11\5\1\0\1\5\1\0\4\5\24\0\3\5"+
    "\1\0\1\5\1\301\1\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\1\5\1\302\17\5"+
    "\1\0\3\5\2\0\12\5\4\0\3\5\1\303\5\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\21\5\1\0\3\5\2\0\12\5\4\0\11\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\1\5\1\304\17\5\1\0\3\5\2\0\12\5"+
    "\4\0\3\5\1\305\5\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\16\5\1\306\2\5"+
    "\1\0\3\5\2\0\12\5\4\0\11\5\1\0\1\5"+
    "\1\0\4\5\24\0\3\5\1\0\3\5\1\0\12\5"+
    "\1\307\6\5\1\0\3\5\2\0\12\5\4\0\11\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\1\310\20\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\1\5\1\311\1\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\1\312\20\5\1\0\3\5"+
    "\2\0\12\5\4\0\10\5\1\313\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\1\5\1\314\2\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\1\5\1\315\1\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\2\5\1\316\6\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\12\5\1\317\6\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\1\5\1\320\1\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\1\5\1\320\2\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\7\5\1\321\11\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\1\5\1\322"+
    "\2\5\24\0\3\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\3\5\1\323\5\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\1\5\1\324"+
    "\7\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\6\5\1\325\2\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\17\5\1\326\1\5\1\0"+
    "\3\5\2\0\12\5\4\0\4\5\1\327\4\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\10\0\1\330\114\0"+
    "\2\5\1\331\6\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\6\5\1\332\2\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\5\5\1\333\3\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\1\5\1\334\1\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\2\5\1\335\6\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\4\5\1\333\5\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\12\5\1\336"+
    "\6\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\15\5\1\337\3\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\1\5\1\322\1\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\1\5\1\340\17\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\5\5\1\321"+
    "\13\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\1\341\20\5\1\0\3\5\2\0\12\5\4\0\10\5"+
    "\1\341\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\20\5\1\342\1\0\3\5\2\0\12\5"+
    "\4\0\11\5\1\0\1\5\1\0\4\5\24\0\3\5"+
    "\1\0\3\5\1\0\21\5\1\0\1\343\2\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\1\344\2\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\4\5"+
    "\24\0\1\5\1\345\1\5\1\0\3\5\1\0\21\5"+
    "\1\0\3\5\2\0\12\5\4\0\11\5\1\0\1\5"+
    "\1\0\4\5\24\0\3\5\1\0\3\5\1\0\16\5"+
    "\1\346\2\5\1\0\3\5\2\0\12\5\4\0\11\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\16\5\1\347\2\5\1\0\3\5\2\0\12\5"+
    "\4\0\11\5\1\0\1\5\1\0\4\5\24\0\3\5"+
    "\1\0\3\5\1\0\12\5\1\350\6\5\1\0\3\5"+
    "\2\0\12\5\4\0\4\5\1\351\4\5\1\0\1\5"+
    "\1\0\4\5\24\0\3\5\1\0\3\5\1\0\21\5"+
    "\1\0\3\5\2\0\12\5\4\0\1\5\1\347\7\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\21\5\1\0\3\5\2\0\12\5\4\0\11\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\12\5\1\352\6\5\1\0\3\5\2\0\12\5"+
    "\4\0\4\5\1\352\4\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\1\353\2\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\4\5\1\354\4\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\10\5\1\355"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\21\5\1\0\3\5\2\0\12\5\4\0\11\5"+
    "\1\0\1\5\1\0\4\5\24\0\3\5\1\0\3\5"+
    "\1\0\17\5\1\356\1\5\1\0\3\5\2\0\12\5"+
    "\4\0\1\5\1\357\7\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\21\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\1\5"+
    "\1\360\2\5\24\0\3\5\1\0\3\5\1\0\21\5"+
    "\1\0\3\5\2\0\12\5\23\0\1\361\101\0\10\5"+
    "\1\362\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\1\5\1\363\2\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\364\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\365\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\1\5\1\366\1\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\16\5\1\357"+
    "\2\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\12\5\1\354\6\5\1\0\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\367\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\370\3\5\2\0\12\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\1\5\1\371\1\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\1\372\20\5\1\0\3\5"+
    "\2\0\12\5\4\0\11\5\1\0\1\5\1\0\4\5"+
    "\24\0\3\5\1\0\3\5\1\0\1\355\20\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\373"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\374"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\15\5\1\375"+
    "\3\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\3\5\1\376\6\5\4\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\17\5\1\377\1\5\1\0\3\5\2\0"+
    "\12\5\4\0\4\5\1\u0100\4\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\17\5\1\u0101"+
    "\1\5\1\0\3\5\2\0\12\5\103\0\1\u0102\121\0"+
    "\1\u0103\20\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\15\5\1\u0104\3\5\1\0"+
    "\3\5\2\0\12\5\54\0\1\u0105\56\0\1\u0106\112\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\15\5\1\u0107\3\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\12\5\1\u0108\6\5\1\0"+
    "\3\5\2\0\12\5\103\0\1\u0109\121\0\1\u010a\20\0"+
    "\11\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\1\5\1\376"+
    "\10\5\4\0\4\5\1\u010b\4\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\17\5\1\u010c"+
    "\1\5\1\0\3\5\2\0\12\5\4\0\4\5\1\u010d"+
    "\4\5\1\0\1\5\1\0\4\5\24\0\3\5\1\0"+
    "\3\5\1\0\21\5\1\0\3\5\2\0\12\5\117\0"+
    "\1\u010e\121\0\1\u010e\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\12\5\1\u010b"+
    "\6\5\1\0\3\5\2\0\12\5\60\0\1\u010f\54\0"+
    "\1\u010f\110\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\12\5\1\u0110\6\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\15\5\1\u0111"+
    "\3\5\1\0\3\5\2\0\12\5\117\0\1\u0112\121\0"+
    "\1\u0112\4\0\1\5\1\u0113\7\5\1\0\1\5\1\0"+
    "\4\5\24\0\3\5\1\0\3\5\1\0\21\5\1\0"+
    "\3\5\2\0\12\5\4\0\11\5\1\0\1\5\1\0"+
    "\4\5\24\0\2\5\1\u0114\1\0\3\5\1\0\21\5"+
    "\1\0\3\5\2\0\12\5\4\0\11\5\1\0\1\5"+
    "\1\0\4\5\24\0\1\u0115\2\5\1\0\3\5\1\0"+
    "\21\5\1\0\3\5\2\0\12\5\4\0\11\5\1\0"+
    "\1\5\1\0\4\5\24\0\3\5\1\0\3\5\1\0"+
    "\16\5\1\u0113\2\5\1\0\3\5\2\0\12\5\4\0"+
    "\5\5\1\u0116\3\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\12\5\4\0\11\5\1\0\1\5\1\0\4\5\24\0"+
    "\3\5\1\0\3\5\1\0\21\5\1\0\3\5\2\0"+
    "\4\5\1\u0116\5\5\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[17982];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\10\1\1\0\4\1\2\0\1\1\6\11"+
    "\1\0\1\1\6\11\3\1\1\0\3\1\1\0\15\1"+
    "\1\11\5\1\3\11\1\0\15\1\1\0\4\1\2\11"+
    "\1\0\3\11\2\1\1\11\7\1\1\11\23\1\1\11"+
    "\24\1\1\0\6\1\1\11\42\1\1\0\42\1\1\0"+
    "\30\1\1\11\2\1\2\0\1\1\2\0\2\1\2\0"+
    "\5\1\2\0\1\1\2\0\2\1\2\0\3\1\2\11"+
    "\2\1\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[278];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private StringBuffer str;
//	private String identifier;
	private SBQLSymbolFactory sf = new SBQLSymbolFactory();
	
	private Token createToken(int id) {
		return createToken(id, yytext());
	}
	
	private Token createToken(int id, Object o) {
		return new Token(id, yyline, yycolumn, new SyntaxTreeNode(o, yychar));
	}
	
	public int getPos() {
		return zzMarkedPos;	
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 186) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 51: 
          { return createToken(COUNT				);
          }
        case 63: break;
        case 29: 
          { return createToken(MORE_OR_EQUAL		);
          }
        case 64: break;
        case 26: 
          { return createToken(STRING_LITERAL, yytext().substring(1,yytext().length()-1)) ;
          }
        case 65: break;
        case 2: 
          { Token t = createToken(ParserSym.IDENTIFIER);
		return t;
          }
        case 66: break;
        case 39: 
          { return createToken(NEW				);
          }
        case 67: break;
        case 7: 
          { return createToken(MULTIPLY			);
          }
        case 68: break;
        case 62: 
          { return createToken(INSTANCEOF		);
          }
        case 69: break;
        case 25: 
          { return createToken(RANGE				);
          }
        case 70: break;
        case 31: 
          { return createToken(AND				);
          }
        case 71: break;
        case 17: 
          { return createToken(MORE				);
          }
        case 72: break;
        case 28: 
          { return createToken(NOT_EQUALS			);
          }
        case 73: break;
        case 22: 
          { return createToken(QUESTION_MARK		);
          }
        case 74: break;
        case 61: 
          { return createToken(INTERSECT			);
          }
        case 75: break;
        case 15: 
          { return createToken(LEFT_BOX_BRACKET	);
          }
        case 76: break;
        case 54: 
          { return createToken(EXISTS				);
          }
        case 77: break;
        case 50: 
          { return createToken(MINUS_FUNCTION		);
          }
        case 78: break;
        case 12: 
          { return createToken(RIGHT_ROUND_BRACKET);
          }
        case 79: break;
        case 58: 
          { return createToken(ORDER_BY			);
          }
        case 80: break;
        case 21: 
          { return createToken(COLON				);
          }
        case 81: break;
        case 8: 
          { return createToken(DIVIDE				);
          }
        case 82: break;
        case 30: 
          { return createToken(OR					);
          }
        case 83: break;
        case 41: 
          { return createToken(MAX				);
          }
        case 84: break;
        case 13: 
          { return createToken(LEFT_CURLY_BRACKET	);
          }
        case 85: break;
        case 27: 
          { return createToken(EQUALS				);
          }
        case 86: break;
        case 11: 
          { return createToken(LEFT_ROUND_BRACKET	);
          }
        case 87: break;
        case 49: 
          { return createToken(DEREF				);
          }
        case 88: break;
        case 34: 
          { return createToken(FORALL				);
          }
        case 89: break;
        case 23: 
          { return createToken(AS					);
          }
        case 90: break;
        case 38: 
          { return createToken(SUM				);
          }
        case 91: break;
        case 24: 
          { return createToken(IN					);
          }
        case 92: break;
        case 55: 
          { return createToken(STRUCT				);
          }
        case 93: break;
        case 14: 
          { return createToken(RIGHT_CURLY_BRACKET);
          }
        case 94: break;
        case 32: 
          { return createToken(LESS_OR_EQUAL		);
          }
        case 95: break;
        case 3: 
          { return createToken(DOT				);
          }
        case 96: break;
        case 1: 
          { int val;
		try {
			val = Integer.parseInt(yytext());
		}
		catch (Exception e) {
			throw new RuntimeException(e.getMessage());
		}
		return createToken(INTEGER_LITERAL, new Integer(val));
          }
        case 97: break;
        case 43: 
          { return createToken(BAG				);
          }
        case 98: break;
        case 36: 
          { return createToken(FORANY				);
          }
        case 99: break;
        case 53: 
          { return createToken(UNIQUE				);
          }
        case 100: break;
        case 48: 
          { return createToken(UNION				);
          }
        case 101: break;
        case 44: 
          { boolean val;
		try {
			val = Boolean.parseBoolean(yytext());
		}
		catch (Exception e) {
			throw new RuntimeException(e.getMessage());
		}
		return createToken(BOOLEAN_LITERAL, new Boolean(val));
          }
        case 102: break;
        case 19: 
          { return createToken(COMA				);
          }
        case 103: break;
        case 16: 
          { return createToken(RIGHT_BOX_BRACKET	);
          }
        case 104: break;
        case 56: 
          { return createToken(FOREACH			);
          }
        case 105: break;
        case 6: 
          { return createToken(MINUS				);
          }
        case 106: break;
        case 47: 
          { return createToken(USING		);
          }
        case 107: break;
        case 60: 
          { return createToken(CLOSE_BY			);
          }
        case 108: break;
        case 45: 
          { return createToken(GROUPBY_DESC		);
          }
        case 109: break;
        case 9: 
          { return createToken(MODULO				);
          }
        case 110: break;
        case 52: 
          { return createToken(WHERE				);
          }
        case 111: break;
        case 37: 
          { return createToken(AVG				);
          }
        case 112: break;
        case 5: 
          { return createToken(PLUS				);
          }
        case 113: break;
        case 20: 
          { return createToken(SEMICOLON			);
          }
        case 114: break;
        case 18: 
          { return createToken(LESS				);
          }
        case 115: break;
        case 59: 
          { return createToken(GROUP_AS			);
          }
        case 116: break;
        case 10: 
          { return createToken(NOT				);
          }
        case 117: break;
        case 33: 
          { double val;
		try {
			val = Double.parseDouble(yytext());
		}
		catch (Exception e) {
			throw new RuntimeException(e.getMessage());
		}
		return createToken(DOUBLE_LITERAL, new Double(val));
          }
        case 118: break;
        case 57: 
          { return createToken(SEQUENCE			);
          }
        case 119: break;
        case 46: 
          { return createToken(JOIN				);
          }
        case 120: break;
        case 40: 
          { return createToken(CHAR_LITERAL, yytext().charAt(1)) ;
          }
        case 121: break;
        case 42: 
          { return createToken(MIN				);
          }
        case 122: break;
        case 4: 
          { 
          }
        case 123: break;
        case 35: 
          { return createToken(GROUPBY_ASC		);
          }
        case 124: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	return createToken(ParserSym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
