
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 20 19:53:01 CET 2015
//----------------------------------------------------

package pl.wcislo.sbql4j.lang.parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int GROUP_AS = 44;
  public static final int FORALL = 40;
  public static final int DIVIDE = 13;
  public static final int STRING_LITERAL = 8;
  public static final int RIGHT_BOX_BRACKET = 54;
  public static final int MORE_OR_EQUAL = 26;
  public static final int CHAR_LITERAL = 9;
  public static final int EQUALS = 16;
  public static final int USING = 62;
  public static final int GROUPBY_DESC = 7;
  public static final int MINUS_FUNCTION = 47;
  public static final int FORANY = 41;
  public static final int LESS = 25;
  public static final int MINUS = 11;
  public static final int WHERE = 33;
  public static final int INSTANCEOF = 61;
  public static final int BOOLEAN_LITERAL = 4;
  public static final int SEMICOLON = 55;
  public static final int NOT = 45;
  public static final int AND = 24;
  public static final int RANGE = 58;
  public static final int CLOSE_BY = 39;
  public static final int LESS_OR_EQUAL = 27;
  public static final int IN = 31;
  public static final int OR = 23;
  public static final int BAG = 35;
  public static final int QUESTION_MARK = 59;
  public static final int PLUS = 10;
  public static final int MULTIPLY = 12;
  public static final int LEFT_CURLY_BRACKET = 51;
  public static final int MIN = 28;
  public static final int DOT = 32;
  public static final int LEFT_ROUND_BRACKET = 49;
  public static final int EOF = 0;
  public static final int NEW = 57;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int MODULO = 14;
  public static final int EXISTS = 46;
  public static final int JOIN = 42;
  public static final int LEFT_BOX_BRACKET = 53;
  public static final int UNIQUE = 18;
  public static final int AVG = 21;
  public static final int COLON = 60;
  public static final int FOREACH = 56;
  public static final int UNION = 19;
  public static final int ORDER_BY = 38;
  public static final int NOT_EQUALS = 17;
  public static final int SUM = 20;
  public static final int SEQUENCE = 36;
  public static final int DOUBLE_LITERAL = 3;
  public static final int INTERSECT = 48;
  public static final int AS = 43;
  public static final int COUNT = 22;
  public static final int STRUCT = 37;
  public static final int GROUPBY_ASC = 6;
  public static final int RIGHT_CURLY_BRACKET = 52;
  public static final int MAX = 29;
  public static final int DEREF = 34;
  public static final int MORE = 15;
  public static final int RIGHT_ROUND_BRACKET = 50;
  public static final int INTEGER_LITERAL = 2;
  public static final int IDENTIFIER = 5;
}

