
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 24 17:13:55 CET 2009
//----------------------------------------------------

package pl.wcislo.sbql4j.lang.parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int GROUP_AS = 43;
  public static final int FORALL = 39;
  public static final int DIVIDE = 12;
  public static final int STRING_LITERAL = 8;
  public static final int MORE_OR_EQUAL = 25;
  public static final int EQUALS = 15;
  public static final int GROUPBY_DESC = 7;
  public static final int MINUS_FUNCTION = 46;
  public static final int FORANY = 40;
  public static final int JAVA_PARAM = 36;
  public static final int LESS = 24;
  public static final int MINUS = 10;
  public static final int WHERE = 32;
  public static final int BOOLEAN_LITERAL = 4;
  public static final int SEMICOLON = 52;
  public static final int NOT = 44;
  public static final int AND = 23;
  public static final int CLOSE_BY = 38;
  public static final int LESS_OR_EQUAL = 26;
  public static final int IN = 30;
  public static final int OR = 22;
  public static final int BAG = 34;
  public static final int PLUS = 9;
  public static final int MULTIPLY = 11;
  public static final int LEFT_CURLY_BRACKET = 50;
  public static final int MIN = 27;
  public static final int DOT = 31;
  public static final int LEFT_ROUND_BRACKET = 48;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int MODULO = 13;
  public static final int EXISTS = 45;
  public static final int JOIN = 41;
  public static final int UNIQUE = 17;
  public static final int AVG = 20;
  public static final int FOREACH = 53;
  public static final int UNION = 18;
  public static final int ORDER_BY = 37;
  public static final int NOT_EQUALS = 16;
  public static final int SUM = 19;
  public static final int DOUBLE_LITERAL = 3;
  public static final int INTERSECT = 47;
  public static final int AS = 42;
  public static final int COUNT = 21;
  public static final int STRUCT = 35;
  public static final int GROUPBY_ASC = 6;
  public static final int RIGHT_CURLY_BRACKET = 51;
  public static final int MAX = 28;
  public static final int DEREF = 33;
  public static final int MORE = 14;
  public static final int RIGHT_ROUND_BRACKET = 49;
  public static final int INTEGER_LITERAL = 2;
  public static final int IDENTIFIER = 5;
}

